title: "PSR - Power View"
remote_theme: fabric-io-rodrigues/just-the-docs
 
#force text + logo
psr_model: "Power View"
logo: assets/images/psr_logo.png

#adding zoom in images
zoom_img_enabled: true

#dark/light mode
change_color_enabled: true
#color_scheme: "dark"

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"
